# Generated by Django 6.1 on 2026-08-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumaccess',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
