# Generated by Django 4.2.30 on 2026-08-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='ResumePro', max_length=100)),
                ('site_tagline', models.CharField(blank=True, default='Build a Professional Resume That Gets Noticed', max_length=255)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('primary_color', models.CharField(default='#4f46e5', help_text='e.g. #4f46e5 (Indigo)', max_length=20)),
                ('secondary_color', models.CharField(default='#334155', help_text='e.g. #334155 (Slate)', max_length=20)),
                ('footer_text', models.TextField(blank=True, default='© 2026 ResumePro. All rights reserved.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
